change to ts
Yanseses/react-burger pull request #7
Opened 2023-01-18 13:27 UTC by Yanseses

2023-01-18 14:43 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по типизации вашего проекта, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует улучшить типизацию для функции `checkResponse`, чтобы воспользоваться полностью возможностями TS для проверки качества и корректности вашего кода (подробнее в комментариях к файлу);
- **(Не относится к Redux файлам сейчас):** Использование типа `any` в большинстве случае **нецелесообразно**, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными (см. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)
- **(Не относится к Redux файлам сейчас):** В проекте присутствуют **отключения линтера** с помощью директивы `// @ts-ignore`. Такой подход считается плохой практикой и должен использоваться только в крайних случаях, когда по-другому не получается объяснить TS, как ему понять данный код корректно.
- Не следует выносить типы описывающие пропсы компонентов в отдельный файл, храните их рядом. Исключение составляют только те, которые переиспользуются в нескольких местах

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

**Обращаю ваше внимание,** что не следует вносить изменения в работу, если вы отправили её на проверку, дождитесь ревью и на следующей итерации проведите необходимые действия, чтобы в процессе проверки не были упущены какие-то важные детали.

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-01-18 14:43 UTC, randomroot commented on src/components/AppHeader/Header.tsx
> +const Header = (): JSX.Element => {
🟡 **Можно улучшить:**

**Здесь и далее по коду:** Имеет смысл использовать специальный интерфейс, обозначающий функциональные компоненты:

```ts
const Header: FC = () => {
  ...
}
```

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +          ? [order.buns._id, ...order.main.map((el: any) => el._id), order.buns._id]
🔴 **Нужно исправить:**

Следует указать конкретную типизацию для параметра `el`, т.к. в данном случае в массиве `main` будут содержаться ингредиенты `IIngridient`

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorBuns/ConstructorBuns.tsx
> +export default function ConstructorBuns({ type }: any){
🔴 **Нужно исправить:**

Следует указать конкретную типизацию для пропсов данного компонента с помощью типа или интерфейса:

```ts

interface IProps {
  type: string
}

export default function ConstructorBuns({ type }: IProps)
```

или преобразовав компонент в константу, вместо функции и использовать интерфейс `FC`:

```ts
const ConstructorBuns: FC<IProps> = ({ type }) => {
  ...
}
```

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMain.tsx
> +    drop(item: any) {
🔴 **Нужно исправить:**

Следует указать конкретную типизацию для данного параметра, с учетом передаваемых значений (например `index` и `IIngredient`)

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMainItem/ConstructorMainItem.tsx
> +    hover: (item: any, monitor) => {
🔴 **Нужно исправить:**

Аналогично `ConstructorMain` следует прописать конкретную типизацию, вместо `any`

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMainItem/ConstructorMainItem.tsx
> +
🔴 **Нужно исправить:**

Не следует использовать данный интерфейс, т.к. он не описывает "функцию" в обычном понимании, а объект с ключом `name` (попробуйте нажать на описание, чтобы посмотреть исходный код). 
Для функций без параметров используйте `() => void`.

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMainItem/ConstructorMainItem.tsx
> +      // @ts-ignore
🔴 **Нужно исправить:**

Следует заменить типизацию `onClick` и убрать принудительное отключение TS

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMainItem/ConstructorMainItem.tsx
> +      // @ts-ignore
🔴 **Нужно исправить:**

Данное отключение типизации не потребуется, т.к. в пропс `ref` вы можете передать напрямую переменную `ref`, которую вы обозначили выше через хук `useRef`, убрав отдельную переменную `dragDropRef`. Работоспособность функционала сохранится.

```tsx
const ref = useRef<HTMLLIElement>(null);
constructorDragRef(constructorDropRef(ref));

return (
  <li 
    ref={ref}
    ...
  >
  ...
)
```

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerIngridients/BurgerIngridients.tsx
> +export interface IIngridient {
🟡 **Можно улучшить:**

Имеет смысл вынести данный тип в папку `utils`, т.к. он переиспользуется во многих частях вашего проекта

2023-01-18 14:43 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMain.tsx
> +    const clickedElem = e.nativeEvent.path[5].id;
🟡 **Можно улучшить:**

Можно упростить данное выражение, если в функцию `handleRemove` передать не `Event`, а `id` ингредиента, т.к. он известен уже в рамках `ConstructorMainItem`. В этом случае можно будет отказаться от `// @ts-ignore`

2023-01-18 14:43 UTC, randomroot commented on src/utils/checkResponce.ts
>    if(res.ok){
🔴 **Нужно исправить:**

В текущем виде функция `checkResponse` не конкретизирует тип возвращаемого значения в теле ответа, поэтому все последующие функции связанные с ней работают с `any`, что не позволяет TypeScript отследить корректность вашего кода:

![image](https://user-images.githubusercontent.com/15111821/213196395-32f04b51-425b-4339-b26d-c8536a748b7a.png)

**Чтобы улучшить данную ситуацию** вы можете воспользоваться следующим подходом:

На основе всех ответов из API вашего бэкенда вы можете обратить внимание, что они имеют схожую структуру с полем `success`, поэтому воспользовавшись пересечением типов получим универсальную структуру:

```typescript
type TResponse<T> = {
  success: boolean;
} & T;
```

где `T` - тип, в котором описаны остальные ключи запроса, например `{ accessToken: string, refreshToken: string }`, которую можно использовать в функции проверки успешности и вернуть назад конкретный тип, в случае успеха:

```typescript
const checkResponse = <T>(res: Response) => {
  return res.ok ? res.json().then(data => data as TResponse<T>) : Promise.reject(res.status);
};
```

Аналогично затем следует скорректировать `fetch`, чтобы она тоже возвращала корректный тип

2023-01-18 14:43 UTC, randomroot commented on src/services/types/index.ts
> +export type TModal = {
🔴 **Нужно исправить:**

Не следует выносить типы описывающие пропсы компонентов в отдельный файл, храните их рядом. Исключение составляют только те, которые переиспользуются в нескольких местах

2023-01-18 14:43 UTC, randomroot commented on src/components/modal/Modal.tsx
> +export const Modal: FC<PropsWithChildren<TModal>> = ({title, onClose, children}): JSX.Element => {
🟡 **Можно улучшить:**

Указания возвращаемого типа `: JSX.Element` необязательно, т.к. интерфейс `FC` уже описывает, что вернется :)

2023-01-19 10:26 UTC, Yanseses commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMain.tsx
> +    drop(item: any) {
Добрый день
К сожалению данный блок типизировать корректно не удается, так как item может являться объектом с ингридиентами, может являться объектом { index: number }. Такой вариант не срабатывает и выдает ошибку:

``` Тип "(item: IIngridient | { index: number; }) => void" не может быть назначен для типа "(item: unknown, monitor: DropTargetMonitor<unknown, unknown>) => unknown".
  Типы параметров "item" и "item" несовместимы.
    Тип "unknown" не может быть назначен для типа "IIngridient | { index: number; }". ```

Причем странная ситуация, на hover в ConstructorMainItem все работает корректно.
Сейчас волью правки, можно будет посмотреть. Может я что то не так делаю

2023-01-20 10:06 UTC, Yanseses commented on src/utils/checkResponce.ts
>    if(res.ok){
Вот тут немного не понял. По идее дженерики возвращают типы непосредственно которые должны быть внутри. 
Исходя из примера, прокидываем все типы ответа через дженерик, и в случае успеха у нас результат делится на success и на остальные типы, которые пришли от бэка? Тогда получается использовать такой же подход с дженериками в файле с fetch не получится, так как на вход мы получаем ответ от сервера, где у нас идет промис, а после проверки checkResponse мы уже имеем вообще другие типы данных.
Или я в чем то ошибаюсь?
Заранее спасибо за ответ!

2023-01-21 09:07 UTC, randomroot commented on src/components/BurgerIngridients/Ingridients/IngridientsItem/IngridientsItem.tsx
> +      { __v > 0 && (
🟡 **Можно улучшить:**

Обратите внимание, что поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте.

2023-01-21 09:07 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMain.tsx
> +    drop(item: any) {
Добрый день! Вероятно, это связано с типизацией новых версий `react-dnd`, в которой они либо хотели, чтобы вы самостоятельно прописывали типы, либо в их коде внутри есть ошибка.

_Варианты исправления:_

**Общий совет:**  Разделить `type`, который принимает область на `main` - для новых ингредиентов, и `SORT_INGREDIENT` для перетаскиваемых уже внутри конструктора - тогда в хуки будет падать объект одного и того же типа. 

1) Для исправления ошибок хука следует **прописать типы напрямую**:

![image](https://user-images.githubusercontent.com/15111821/213860101-eeb99118-271e-45a8-b3fe-e9be60eecaa8.png)

или

2) **Понизить версию** библиотеки (например до 14-ой). Там этот момент должен отрабатывать теоретически корректно и в текущем виде.

2023-01-21 09:17 UTC, randomroot commented on src/utils/checkResponce.ts
>    if(res.ok){
Примеры использования подхода с дженериками на примере запроса ингредиентов:

Улучшаем функцию `request`, позволяя ей тоже использовать дженерик и прокидывать в `checkResponse`:

![image](https://user-images.githubusercontent.com/15111821/213860483-2c89b516-e2ae-4bc2-ad5e-b22856e47489.png)

Вызываем запрос, где передаем в функцию аргумент, что ожидается в теле и в результате получаем в `res` нужный тип:

![image](https://user-images.githubusercontent.com/15111821/213860471-f1f88ce6-8b7b-4d1b-8f19-e2cbd5fd3376.png)

2023-01-21 09:25 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- Следует скорректировать код на основе ответов к вашим вопросам в рамках предыдущего ревью;
- Верхний ингредиент в конструкторе невозможно перетащить на другое место. Это связано с тем, что проверка `if (item.index)` при значении `index` равным нулю вернет `false` из-за автоматического преобразования типов в JS. (см. https://disk.yandex.ru/i/i09hLdKs1-2KSw);

**Хорошего вам дня и настроения!** 🐈

2023-01-22 14:56 UTC, Yanseses commented on src/components/BurgerConstructor/ConstructorMain/ConstructorMain.tsx
> +    drop(item: any) {
Сделал по первому варианту. Все тайпинги сработали корректно.
Спасибо!

2023-01-22 14:58 UTC, Yanseses commented on src/utils/checkResponce.ts
>    if(res.ok){
И если правильно понимаю, в следующем спринте нужно будет для всех запросов прописать типы/интерфейсы в которых будут типизированы все поля, получаемые со стороны бэка (кроме единого поля success, которое у нас прописано уже в самом checkResponce)?
Спасибо!

2023-01-22 15:01 UTC, randomroot commented on src/utils/checkResponce.ts
>    if(res.ok){
Да, всё верно, так как в следующем спринте вы будете переводить вашу часть проекта, связанную с Redux на TS, и наработки этого спринта помогут вам безболезненно это сделать :)

2023-01-22 15:30 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-23 12:07 UTC, merged